name: Build
on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
        path: 'source'
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Set up OSS Python SDK
      run: pip install oss2
    - name: Build
      run: |
        mkdir output
        docker run --mount "type=bind,source=$GITHUB_WORKSPACE/source,destination=/imhele/html,readonly=1" \
                   --env "HTML_SOURCE=/imhele/html" \
                   --mount "type=bind,source=$GITHUB_WORKSPACE/output,destination=/imhele/output" \
                   --env "HTML_OUTPUT=/imhele/output" \
                   imhele/html-build
    - name: Deploy
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      env:
        AccessKeyId: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
        AccessKeySecret: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
        EndPoint: ${{ secrets.ALIYUN_OSS_END_POINT }}
        BucketName: ${{ secrets.ALIYUN_OSS_BUCKET_NAME }}
      run: python $GITHUB_WORKSPACE/deploy-oss.py
